name: Workflow do Zadania 2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Ustawienie buildx
        uses: docker/setup-buildx-action@v3

      - name: Logowanie do DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Logowanie do ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Budowanie obrazu amd64 do skanowania
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: temp-image:scan
          load: true
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cache:${{ github.sha }}
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cache:${{ github.sha }},mode=max

      - name: Skanowanie obrazu za pomocą Trivy
        uses: aquasecurity/trivy-action@0.13.0
        with:
          image-ref: temp-image:scan
          format: table
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Budowanie i pushowanie obrazu multiarch na ghcr.io
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kacperklusek1/weather_app_chmurki:latest
            ghcr.io/kacperklusek1/weather_app_chmurki:${{ github.sha }}
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cache:${{ github.sha }}
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cache:${{ github.sha }},mode=max
